### PR TITLE
added failing test for partially qualified names

### PR DESCRIPTION
**Pull request by weirdan**
Refs phpactor/phpactor#427

### CODE REVIEW

**Comment by weirdan** [comment]
I expected travis to fail, but not in this way. @dantleech you may want to take a look at these failures, travis can't clone this repo atm.

**Comment by dantleech** [comment]
Ah, initially I was using custom repository locations in `composer.json` which doesn't seem to work so well with 3rd party PRs. Fixed that now if you wanted to rebase.

**Comment by weirdan** [comment]
Yay, now it fails the way it's meant to fail.

**Comment by dantleech** [comment]
It seems I neglected this one, was the issue fixed?

**Comment by weirdan** [comment]
The test is still failing, so I suppose it wasn't.

**Pull request closed without merging**
