### PR TITLE
Refactor missing assignments to missing properties

### PR DESCRIPTION
**Pull request by greg0ire**
Refs https://github.com/phpactor/phpactor/issues/256

### CODE REVIEW

**Comment by greg0ire** [comment]
@dantleech Travis asks for credentials. Maybe it will work if you do the PR yourself?

**Comment by dantleech** [comment]
Yeah, it's not on composer currently, I guess that's why. merging, as phpactor uses a composer lock anyway :)

**Comment by dantleech** [comment]
btw. Phpactor will need to be updated to use the new class name.

**Comment by dantleech** [comment]
Actually, these builds don't work at all :man_shrugging:

**Comment by greg0ire** [comment]
> 🤷‍♂️

Lol is this supposed to be emoji composition? I see 2 separate emojis

**Comment by dantleech** [comment]
asdasd

Obviously I need to learn the ascii shrug.

**Comment by greg0ire** [comment]
This can help, but beware of escape sequences: https://textfac.es/

**Pull request merged**
